// Generated by Wrangler on Tue Apr 23 2024 08:08:41 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	MY_DURABLE_OBJECT: DurableObjectNamespace;
}

declare module 'cloudflare:test' {
	interface ProvidedEnv extends Env {}
}
